version: "3.9"

services:
  web:
    build: ../../backend/backend-assignment
    command: "java -jar /app.jar"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: nordnet.jfrog.io/docker-hub/postgres:14.0
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data/