spring:
  datasource:
    url: jdbc:h2:file:./data/orderdb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true

  jackson:
    default-property-inclusion: non_null

server:
  error:
    include-message: always
